[pytest]
env_override_existing_values = 1
env_files =
    .env

addopts =
    -vv
    --strict-markers -rfE
    --basetemp=test/tmp

markers =
    slow: mark test as long-running
    localdata: test data not always available
