name: Infrastructure Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "What environment to build or promote and deploy"
        required: true
        type: choice
        default: "dev"
        options:
          - "dev"
          - "qa"
          - "prod"

permissions:
  contents: read

concurrency:
  group: hedwig-workflow-api-${{ inputs.environment }}
  cancel-in-progress: false

env:
  HOME: /root
  SPACES_CLI_CICD: true
  SPACES_SOLUTION_FILE: hedwig.spaces-solution.yaml
  SPACES_SOLUTION_ROLE: cicd-runner-admin

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    env:
      SPACES_SOLUTION_ENV: ${{ inputs.environment }}
    name: Deploy
    runs-on: [self-hosted, linux]
    defaults:
      run:
        working-directory: deploy/hedwig-workflow-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Build Agent SSH Key
        uses: niaid/monarch-actions-key-writer@v2
        with:
          key: ${{ secrets.NIAID_BUILD_AGENTS_SSH_KEY }}
          known_hosts: ${{ secrets.NIAID_KNOWN_HOSTS }}
          if_key_exists: replace
      - name: Install Spaces CLI
        run: curl -s https://s3.amazonaws.com/pubfiles-coreinfra-0d49b49f3ba3/spaces-cli/install.sh | bash
      - name: Export PATH
        run: echo "$PATH:/root/.spaces-cli/bin" >> $GITHUB_PATH
      - name: Update Spaces CLI
        run: spaces update stable
      - name: Initialize
        run: spaces task -- init
      - name: Build for Dev
        if: ${{ inputs.environment == 'dev' }}
        run: |
          spaces task -- build
          spaces task -- scan
          spaces task -- deploy
      - name: Promote to QA and Deploy
        if: ${{ inputs.environment == 'qa' }}
        run: |
          spaces task -- promote-image -- dev qa
          spaces task -- deploy
      - name: Promote to Prod and Deploy
        if: ${{ inputs.environment == 'prod' }}
        run: |
          spaces task -- promote-image -- qa prod
          spaces task -- deploy
